Update `occ` and `occ-cron` scripts

diff --git a/src/usr/local/bin/occ b/src/usr/local/bin/occ
--- a/src/usr/local/bin/occ
+++ b/src/usr/local/bin/occ
@@ -10,8 +10,16 @@
 # SPDX-License-Identifier: MIT
 # License-Filename: LICENSE
 
-if [ "$(id -un)" != "www-data" ]; then
-    exec su -p -s /bin/sh www-data -c 'php -d memory_limit=2G -f /var/www/html/occ -- "$@"' -- '/bin/sh' "$@"
+set -eu
+
+[ -e /var/www/html/occ ] || { echo "Unable to run \`occ\`: No such file or directory" >&2 ; exit 1 ; }
+[ -f /var/www/html/occ ] || { echo "Unable to run \`occ\`: Not a file" >&2 ; exit 1 ; }
+
+RUN_AS="$(stat -c %U /var/www/html/occ)"
+[ -n "$RUN_AS" ] && [ "$RUN_AS" != "UNKNOWN" ] || { echo "Unable to run \`occ\`: Failed to determine www-data user" >&2 ; exit 1 ; }
+
+if [ "$(id -u)" = 0 ]; then
+    exec su -p "$RUN_AS" -s /bin/sh -c 'exec php -d memory_limit=2G -f /var/www/html/occ -- "$@"' -- '/bin/sh' "$@"
 else
     exec php -d memory_limit=2G -f /var/www/html/occ -- "$@"
 fi
diff --git a/src/usr/local/bin/occ-cron b/src/usr/local/bin/occ-cron
--- a/src/usr/local/bin/occ-cron
+++ b/src/usr/local/bin/occ-cron
@@ -10,13 +10,21 @@
 # SPDX-License-Identifier: MIT
 # License-Filename: LICENSE
 
+set -eu
+
 if [ "$(occ status 2> /dev/null | sed -ne 's/^  - installed: \(.*\)$/\1/p')" != "true" ]; then
     echo "Nextcloud is not installed - cronjobs are not available" >&2
-    exit 0
+    exit 1
 fi
 
-if [ "$(id -un)" != "www-data" ]; then
-    exec su -p -s /bin/sh www-data -c 'php -d memory_limit=2G -f /var/www/html/cron.php' -- '/bin/sh'
+[ -e /var/www/html/cron.php ] || { echo "Unable to run \`occ-cron\`: No such file or directory" >&2 ; exit 1 ; }
+[ -f /var/www/html/cron.php ] || { echo "Unable to run \`occ-cron\`: Not a file" >&2 ; exit 1 ; }
+
+RUN_AS="$(stat -c %U /var/www/html/cron.php)"
+[ -n "$RUN_AS" ] && [ "$RUN_AS" != "UNKNOWN" ] || { echo "Unable to run \`occ-cron\`: Failed to determine www-data user" >&2 ; exit 1 ; }
+
+if [ "$(id -u)" = 0 ]; then
+    exec su -p "$RUN_AS" -s /bin/sh -c 'exec php -d memory_limit=2G -f /var/www/html/cron.php' -- '/bin/sh'
 else
     exec php -d memory_limit=2G -f /var/www/html/cron.php
 fi
